config/routes.rb
Rails.application.routes.draw do
  # get 'students/index'
  root :to => 'students#index'
  resources :students

  get '/new_student' => 'students#new'
  get '/all' => 'students#index', as: 'all_students'
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates_presence_of :name, :weight, :height, :color, :gpa
  validates_numericality_of :weight, :height, :gpa
  validates_inclusion_of :weight, in: 100..400
  validates_exclusion_of :weight, in: 0..99
  validates_inclusion_of :height, in: 135..225
  validates_exclusion_of :height, in: 0..134
  validates_inclusion_of :gpa, in: 0..4.3
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :get_student, only: [:edit, :update, :destroy, :show]
  def get_student
    @student = Student.find(params[:id])
  end

  def index #list all students
    @students = Student.all
  end

  def edit #show an edit format
    @color = @student.color
  end

  def new #new student form
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
      if @student.save
        redirect_to students_path
      else
        redirect_to(new_student_path, alert: "Invalid properties, are there any blanks?")
      end
    end

  def show #show a single student
    respond_to do |format|
      format.html
      format.json { render json: @student }
      format.xml  { render xml: @student  }
    end
  end

  def update
    if @student.update_attributes(params.require(:student).permit(
      :name, :weight, :height, :color, :gpa))
      redirect_to(students_path, notice: "Student successfully updated")
    else
      redirect_to(edit_student_path, alert: "Invalid properties, are there any blanks?")
    end
  end

  def destroy
    if @student.destroy
      redirect_to(students_path, notice: "Student successfully destroyed")
    else
      redirect_to(students_path, alert: "Failed to destroy student")
    end
  end

  private
  def student_params
    params.require(:student).permit(
      :name, :weight, :height, :color, :gpa)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assign2</title>
    <!-- enable jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <!-- font for sticky notes -->
    <link href="https://fonts.googleapis.com/css?family=Waiting+for+the+Sunrise" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body onload=changeColor(@color)>
    <ul>
      <li><%= link_to "All Students", students_path %></li>
      <li><%= link_to "New Student", new_student_path %></li>
      <li>
      <% if flash[:notice] %>
        <div id="notice"><%= flash[:notice] %></div>
      <%end%>
      </li>
      <% if flash[:alert] %>
        <div id="alert"><%= flash[:alert] %></div>
      <%end%>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<div class="formPageWrapper">
<div class="formPageBG" id="formPageBG" style="background-color: <%=@student.color%>">
<h1 class="pageTitle">Edit student</h1>

<%= form_for @student, html: {autocomplete: "off"} do |f| %>
<div class="field">
<%= f.label :name %><br/>
<%= f.text_field :name, maxlength: 18 %>
</div>

<div class="field">
<%= f.label :gpa, "GPA (0.0 - 4.3)" %><br/>
<%= f.number_field :gpa, step: 0.1 %>
</div>

<div class="field">
<%= f.label :weight, "Weight (100lb - 400lb)" %><br/>
<%= f.number_field :weight %>
</div>

<div class="field">
<%= f.label :height, "Height (135cm-225cm)" %><br/>
<%= f.number_field :height %>
</div>

<div class="field">
<%= f.radio_button :color, '#ADD8E6', onClick: "changeColor('#ADD8E6')"%>
<span class="colorLabelBlue" id="colorLabel"><%= f.label :color, 'Blue'%></span>
<%= f.radio_button :color, '#FFB6C1', onClick: "changeColor('#FFB6C1')"%>
<span class="colorLabelPink" id="colorLabel"><%= f.label :color, 'Pink'%></span>
<%= f.radio_button :color, '#FFFFA5', onClick: "changeColor('#FFFFA5')"%>
<span class="colorLabelYellow" id="colorLabel"><%= f.label :color, 'Yellow'%></span>
<%= f.radio_button :color, '#FDFDFD', onClick: "changeColor('#FDFDFD')"%>
<span class="colorLabelWhite" id="colorLabel"><%= f.label :color, 'White'%></span>
</div>

<div class="action">
  <%= f.submit "Update", style: "background-color: #{@student.color}", class: "formButton"%>
</div>
<% end %>
</div>
</div>

app/views/students/index.html.erb
<div id="notes">
<% @students.each do |s| %>
<div class="student" style="height:<%=s.height%>px;
  width:<%=s.weight%>px; background-color: <%=s.color%>;">
  <div class="pin"></div><div></div>
  <div class="info">
    <%=s.name.titleize%><br/>
    GPA: <%=s.gpa%>
  </div>
  <span class ="link">
    <%= link_to "Edit", edit_student_path(s) %>
    <%= link_to "Destroy", s, method: :delete %>
    <%= link_to "View", student_path(s) %>
  </span>
  <div class="pin"></div>
</div>
<% end %>
</div>
<!-- sends ruby data to javascript.coffee
<%= content_tag "div", id: "students", data: {students: Student.all} do %>
<%end%> -->

app/views/students/new.html.erb
<div class="formPageWrapper">
<div class="formPageBG">
<h1 class="pageTitle">Create a new student</h1>

<%= form_for @student, html: {autocomplete: "off"} do |f| %>
<div class="field">
<%= f.label :name %><br/>
<%= f.text_field :name, maxlength: 18 %>
</div>

<div class="field">
<%= f.label :gpa, "GPA (0.0 - 4.3)" %><br/>
<%= f.number_field :gpa, step: 0.1 %>
</div>

<div class="field">
<%= f.label :weight, "Weight (100lb - 400lb)" %><br/>
<%= f.number_field :weight %>
</div>

<div class="field">
<%= f.label :height, "Height (135cm-225cm)" %><br/>
<%= f.number_field :height %>
</div>

<div class="field">
<%= f.radio_button :color, '#ADD8E6', onClick: "changeColor('#ADD8E6')"%>
<span class="colorLabelBlue" id="colorLabel"><%= f.label :color, 'Blue'%></span>
<%= f.radio_button :color, '#FFB6C1', onClick: "changeColor('#FFB6C1')"%>
<span class="colorLabelPink" id="colorLabel"><%= f.label :color, 'Pink'%></span>
<%= f.radio_button :color, '#FFFFA5', onClick: "changeColor('#FFFFA5')"%>
<span class="colorLabelYellow" id="colorLabel"><%= f.label :color, 'Yellow'%></span>
<%= f.radio_button :color, '#FDFDFD', onClick: "changeColor('#FDFDFD')"%>
<span class="colorLabelWhite" id="colorLabel"><%= f.label :color, 'White'%></span>
</div>

<div class="action">
  <%= f.submit "Create", style: "background-color: #ADD8E6", class: "formButton"%>
</div>
<% end %>
</div>
</div>

app/views/students/show.html.erb
<div class="viewWrapper">
  <div class="student" id="showStudent" style="background-color: <%=@student.color%>;">
    <div class="info">
      <h2><%=@student.name%></h2>
      GPA: <%=@student.gpa%></br>
      Height: <%=@student.height%>cm</br>
      Weight: <%=@student.weight%>lbs</br>
      Color's hex value: <%=@student.color%>
    </div>
    <div class ="link"><%= link_to "Back", action: "index" %></div>
  </div>
</div>